fragment CampaignsParts on Campaigns {
  hero {
    __typename
    media {
      __typename
      ... on CampaignsHeroMediaImageMedia {
        featureImage
      }
      ... on CampaignsHeroMediaMdxMedia {
        featureMDX
      }
      ... on CampaignsHeroMediaYoutubeMedia {
        featureYoutube
        featureYoutubeTitle
      }
    }
    title
    text
  }
  blocks {
    __typename
    ... on CampaignsBlocksGenericFeature {
      title
      text
    }
  }
}
