fragment CampaignsParts on Campaigns {
  hero {
    __typename
    media {
      __typename
      ... on CampaignsHeroMediaGenericFeature {
        title
        text
      }
    }
    title
    text
  }
  blocks {
    __typename
    ... on CampaignsBlocksGenericFeature {
      title
      text
    }
  }
}
