fragment GlobalsParts on Globals {
  logo
  icon
  navItems {
    __typename
    text
    url
    button
  }
  footer {
    __typename
    logo
    contactFormText {
      __typename
      title
      shortText
    }
    contactDetails
  }
  brand {
    __typename
    colours {
      __typename
      primary
    }
  }
}

fragment ProjectsParts on Projects {
  seo {
    __typename
    title
    description
    socialImage
  }
  title
  backgroundImage
  mainImage
  completionDate
  projectDescription
}

fragment HomeParts on Home {
  seo {
    __typename
    title
    description
    socialImage
  }
  hero {
    __typename
    title
    subtitle
    image
  }
  featuredProjects {
    __typename
    project1 {
      ... on Document {
        id
      }
    }
    project2 {
      ... on Document {
        id
      }
    }
    project3 {
      ... on Document {
        id
      }
    }
  }
}
