//@ts-nocheck
// DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
export function gql(strings: TemplateStringsArray, ...args: string[]): string {
  let str = ''
  strings.forEach((string, i) => {
    str += string + (args[i] || '')
  })
  return str
}
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** References another document, used as a foreign key */
  Reference: any;
  JSON: any;
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String'];
  title?: Maybe<Scalars['String']>;
  basename: Scalars['String'];
  breadcrumbs: Array<Scalars['String']>;
  path: Scalars['String'];
  relativePath: Scalars['String'];
  extension: Scalars['String'];
  template: Scalars['String'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']>;
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean'];
  hasNextPage: Scalars['Boolean'];
  startCursor: Scalars['String'];
  endCursor: Scalars['String'];
};

export type Node = {
  id: Scalars['ID'];
};

export type Document = {
  id: Scalars['ID'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  campaigns: Campaigns;
  campaignsConnection: CampaignsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryCampaignsArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryCampaignsConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String'];
  slug: Scalars['String'];
  label?: Maybe<Scalars['String']>;
  path: Scalars['String'];
  format?: Maybe<Scalars['String']>;
  matches?: Maybe<Scalars['String']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
};

export type DocumentNode = Campaigns;

export type CampaignsHeroMediaGenericFeature = {
  __typename?: 'CampaignsHeroMediaGenericFeature';
  title?: Maybe<Scalars['String']>;
  text?: Maybe<Scalars['JSON']>;
};

export type CampaignsHeroMedia = CampaignsHeroMediaGenericFeature;

export type CampaignsHero = {
  __typename?: 'CampaignsHero';
  media?: Maybe<Array<Maybe<CampaignsHeroMedia>>>;
  title?: Maybe<Scalars['String']>;
  text?: Maybe<Scalars['JSON']>;
};

export type CampaignsBlocksGenericFeature = {
  __typename?: 'CampaignsBlocksGenericFeature';
  title?: Maybe<Scalars['String']>;
  text?: Maybe<Scalars['JSON']>;
};

export type CampaignsBlocks = CampaignsBlocksGenericFeature;

export type Campaigns = Node & Document & {
  __typename?: 'Campaigns';
  hero?: Maybe<CampaignsHero>;
  blocks?: Maybe<Array<Maybe<CampaignsBlocks>>>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type CampaignsConnectionEdges = {
  __typename?: 'CampaignsConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<Campaigns>;
};

export type CampaignsConnection = Connection & {
  __typename?: 'CampaignsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<CampaignsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  updateCampaigns: Campaigns;
  createCampaigns: Campaigns;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String'];
  relativePath: Scalars['String'];
  template?: InputMaybe<Scalars['String']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
  params: DocumentMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
  params: DocumentMutation;
};


export type MutationUpdateCampaignsArgs = {
  relativePath: Scalars['String'];
  params: CampaignsMutation;
};


export type MutationCreateCampaignsArgs = {
  relativePath: Scalars['String'];
  params: CampaignsMutation;
};

export type DocumentMutation = {
  campaigns?: InputMaybe<CampaignsMutation>;
};

export type CampaignsHeroMediaGenericFeatureMutation = {
  title?: InputMaybe<Scalars['String']>;
  text?: InputMaybe<Scalars['JSON']>;
};

export type CampaignsHeroMediaMutation = {
  genericFeature?: InputMaybe<CampaignsHeroMediaGenericFeatureMutation>;
};

export type CampaignsHeroMutation = {
  media?: InputMaybe<Array<InputMaybe<CampaignsHeroMediaMutation>>>;
  title?: InputMaybe<Scalars['String']>;
  text?: InputMaybe<Scalars['JSON']>;
};

export type CampaignsBlocksGenericFeatureMutation = {
  title?: InputMaybe<Scalars['String']>;
  text?: InputMaybe<Scalars['JSON']>;
};

export type CampaignsBlocksMutation = {
  genericFeature?: InputMaybe<CampaignsBlocksGenericFeatureMutation>;
};

export type CampaignsMutation = {
  hero?: InputMaybe<CampaignsHeroMutation>;
  blocks?: InputMaybe<Array<InputMaybe<CampaignsBlocksMutation>>>;
};

export type CampaignsPartsFragment = { __typename?: 'Campaigns', hero?: { __typename: 'CampaignsHero', title?: string | null, text?: any | null, media?: Array<{ __typename: 'CampaignsHeroMediaGenericFeature', title?: string | null, text?: any | null } | null> | null } | null, blocks?: Array<{ __typename: 'CampaignsBlocksGenericFeature', title?: string | null, text?: any | null } | null> | null };

export type CampaignsQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type CampaignsQuery = { __typename?: 'Query', campaigns: { __typename?: 'Campaigns', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'CampaignsHero', title?: string | null, text?: any | null, media?: Array<{ __typename: 'CampaignsHeroMediaGenericFeature', title?: string | null, text?: any | null } | null> | null } | null, blocks?: Array<{ __typename: 'CampaignsBlocksGenericFeature', title?: string | null, text?: any | null } | null> | null } };

export type CampaignsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
}>;


export type CampaignsConnectionQuery = { __typename?: 'Query', campaignsConnection: { __typename?: 'CampaignsConnection', totalCount: number, edges?: Array<{ __typename?: 'CampaignsConnectionEdges', node?: { __typename?: 'Campaigns', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'CampaignsHero', title?: string | null, text?: any | null, media?: Array<{ __typename: 'CampaignsHeroMediaGenericFeature', title?: string | null, text?: any | null } | null> | null } | null, blocks?: Array<{ __typename: 'CampaignsBlocksGenericFeature', title?: string | null, text?: any | null } | null> | null } | null } | null> | null } };

export const CampaignsPartsFragmentDoc = gql`
    fragment CampaignsParts on Campaigns {
  hero {
    __typename
    media {
      __typename
      ... on CampaignsHeroMediaGenericFeature {
        title
        text
      }
    }
    title
    text
  }
  blocks {
    __typename
    ... on CampaignsBlocksGenericFeature {
      title
      text
    }
  }
}
    `;
export const CampaignsDocument = gql`
    query campaigns($relativePath: String!) {
  campaigns(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CampaignsParts
  }
}
    ${CampaignsPartsFragmentDoc}`;
export const CampaignsConnectionDocument = gql`
    query campaignsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String) {
  campaignsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
  ) {
    totalCount
    edges {
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CampaignsParts
      }
    }
  }
}
    ${CampaignsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      campaigns(variables: CampaignsQueryVariables, options?: C): Promise<{data: CampaignsQuery, variables: CampaignsQueryVariables, query: string}> {
        return requester<{data: CampaignsQuery, variables: CampaignsQueryVariables, query: string}, CampaignsQueryVariables>(CampaignsDocument, variables, options);
      },
    campaignsConnection(variables?: CampaignsConnectionQueryVariables, options?: C): Promise<{data: CampaignsConnectionQuery, variables: CampaignsConnectionQueryVariables, query: string}> {
        return requester<{data: CampaignsConnectionQuery, variables: CampaignsConnectionQueryVariables, query: string}, CampaignsConnectionQueryVariables>(CampaignsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (client: TinaClient) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: any,
    client
  ) => Promise<any> = async (doc, vars, _options) => {
    let data = {};
    try {
      data = await client.request({
        query: doc,
        variables: vars,
      });
    } catch (e) {
      // swallow errors related to document creation
      console.warn("Warning: There was an error when fetching data");
      console.warn(e);
    }

    return { data: data?.data, query: doc, variables: vars || {} };
  };

  return requester;
};

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(createClient({ url: "http://localhost:4001/graphql" }))
  );

export const queries = (client: TinaClient) => {
  const requester = generateRequester(client);
  return getSdk(requester);
};

